      integer nmmtbe,nmelbe,nslrbe,nretra,nsenso,nprete
      integer nslrbet,nretrat,npretet
      integer lbe1,lbe2,lbe3,lbe4,lbe5,lbe6,lbe7,lbe8,lbe9,lbe10,
     . lbe11,lbe12,lb10,lb11,lbe0,
     . lretra2d,lslrbe2d,lprete2d,
     . lbarb1,lretra,lslrbe,lprete,lsenso,lacmtr
      common/sbelt/nmmtbe,nmelbe,nslrbe,nretra,nsenso,nprete,
     . nslrbet,nretrat,npretet,
     . lbe1,lbe2,lbe3,lbe4,lbe5,lbe6,lbe7,lbe8,lbe9,lbe10,
     . lbe11,lbe12,lb10,lb11,lbe0,
     . lretra2d,lslrbe2d,lprete2d,
     . lbarb1,lretra,lslrbe,lprete,lsenso,lacmtr
c
      integer nmsbsh,lbe2d,nnmsb0,icsf2db,ip2dblt,nmsb1d
      common/sbelt2d/nmsbsh,lbe2d,nnmsb0,icsf2db,ip2dblt,nmsb1d
